/**
 * lib/pdf/hospital-grade-export.tsx
 * Generates a hospital-grade structured PDF using @react-pdf/renderer.
 * Tables: read by callers via fetchExportData(); this module is a
 *         pure renderer over the ExportData bundle.
 * Auth: callers (export routes) must verify auth before invoking.
 * Sprint: Sprint 13 -- Hospital-Grade PDF Export
 *
 * HIPAA: Returns a binary PDF containing full PHI. Caller must NOT
 * write to disk, log, or cache. Stream the bytes back in the API
 * response and rely on the client to discard. The bilingual
 * disclaimer is rendered on every report so the document is self-
 * describing as a coordination tool, not a medical record.
 */
import * as React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { ExportData } from "./fetch-export-data";

const COLORS = {
  primary: "#2C5F4A",
  accent: "#C4714A",
  muted: "#6B6B6B",
  border: "#E8E2D9",
  text: "#1A1A1A",
  paleSage: "#F0F5F2",
  paleTerra: "#FDF3EE",
} as const;

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, color: COLORS.text, fontFamily: "Helvetica" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  brand: { fontSize: 11, fontFamily: "Helvetica-Bold", color: COLORS.primary },
  smallMuted: { fontSize: 9, color: COLORS.muted },
  patientName: { fontSize: 20, fontFamily: "Helvetica-Bold", color: COLORS.primary, marginBottom: 4 },
  patientMeta: { fontSize: 10, color: COLORS.muted, marginBottom: 2 },
  rule: { borderBottomWidth: 1, borderBottomColor: COLORS.border, marginVertical: 8 },
  sectionHeader: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: COLORS.primary,
    marginTop: 12,
    marginBottom: 6,
  },
  disclaimerBox: {
    borderWidth: 1,
    borderColor: COLORS.accent,
    backgroundColor: COLORS.paleTerra,
    padding: 8,
    marginVertical: 8,
  },
  disclaimerText: { fontSize: 9, color: COLORS.text, lineHeight: 1.4 },
  body: { fontSize: 10, color: COLORS.text, lineHeight: 1.4 },
  bodyMuted: { fontSize: 10, color: COLORS.muted, fontStyle: "italic" },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.primary,
    paddingBottom: 4,
    marginTop: 4,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border,
    paddingVertical: 4,
  },
  th: { fontSize: 9, fontFamily: "Helvetica-Bold", color: COLORS.primary, paddingRight: 6 },
  td: { fontSize: 9, color: COLORS.text, paddingRight: 6 },
  badgeAccent: {
    fontSize: 9,
    color: COLORS.accent,
    fontFamily: "Helvetica-Bold",
  },
  emergencyBox: {
    borderLeftWidth: 3,
    borderLeftColor: COLORS.accent,
    backgroundColor: COLORS.paleTerra,
    padding: 8,
    marginVertical: 6,
  },
  documentItem: {
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border,
    paddingVertical: 6,
  },
  noteCard: {
    backgroundColor: COLORS.paleSage,
    padding: 6,
    marginBottom: 6,
    borderRadius: 2,
  },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 36,
    right: 36,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: COLORS.muted,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.border,
    paddingTop: 4,
  },
  footerCol: { fontSize: 8, color: COLORS.muted },
});

// Exported so tests can verify the exact copy rendered into the PDF
// (the PDF byte stream is compressed by @react-pdf, so substring
// search inside the buffer does not work).
export const DISCLAIMER_EN =
  "This report was generated by Clarifer, a caregiver coordination tool. It is not a medical record and does not constitute medical advice. Please consult your healthcare team for clinical decisions.";

export const DISCLAIMER_ES =
  "Este informe fue generado por Clarifer, una herramienta de coordinacion para cuidadores. No es un registro medico y no constituye consejo medico. Consulte a su equipo de salud para decisiones clinicas.";

/**
 * Computes age from an ISO date string. Returns empty string when the
 * input is null or unparseable so the header gracefully omits age.
 */
function ageFromDob(dob: string | null | undefined): string {
  if (!dob) return "";
  const d = new Date(dob);
  if (Number.isNaN(d.getTime())) return "";
  const now = new Date();
  let age = now.getFullYear() - d.getFullYear();
  const m = now.getMonth() - d.getMonth();
  if (m < 0 || (m === 0 && now.getDate() < d.getDate())) age -= 1;
  return String(age);
}

function fmtDate(iso: string | null | undefined): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString();
}

function fmtDateTime(iso: string | null | undefined): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleString();
}

function Footer({ generatedAt }: { generatedAt: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerCol}>Generated by Clarifer -- clarifer.com</Text>
      <Text
        style={styles.footerCol}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
      <Text style={styles.footerCol}>CONFIDENTIAL -- For clinical use only</Text>
    </View>
  );
}

function HeaderBlock({ data }: { data: ExportData }) {
  const { patient } = data;
  const age = ageFromDob(patient.dob);
  return (
    <>
      <View style={styles.headerRow}>
        <Text style={styles.brand}>{data.orgName || "Clarifer"}</Text>
        <Text style={styles.smallMuted}>MEDICAL SUMMARY REPORT</Text>
      </View>
      <Text style={styles.patientName}>{patient.name ?? "Patient"}</Text>
      <Text style={styles.patientMeta}>
        {patient.dob ? `DOB ${patient.dob}` : "DOB on file"}
        {age ? ` (age ${age})` : ""}
      </Text>
      <Text style={styles.patientMeta}>
        {patient.custom_diagnosis ?? patient.condition_template_id ?? "Diagnosis on file"}
      </Text>
      <Text style={styles.patientMeta}>
        Report generated {fmtDateTime(data.generatedAt)} by {data.generatedBy || "care team"}
      </Text>
      <View style={styles.rule} />
    </>
  );
}

function DisclaimerBlock() {
  return (
    <View style={styles.disclaimerBox}>
      <Text style={styles.disclaimerText}>{DISCLAIMER_EN}</Text>
      <Text style={[styles.disclaimerText, { marginTop: 6 }]}>{DISCLAIMER_ES}</Text>
    </View>
  );
}

function EmergencyBlock({ data }: { data: ExportData }) {
  const { patient } = data;
  if (!patient.emergency_card_enabled) return null;
  const allergies = patient.allergies && patient.allergies.length > 0 ? patient.allergies.join(", ") : null;
  return (
    <View>
      <Text style={styles.sectionHeader}>Emergency information</Text>
      <View style={styles.emergencyBox}>
        {patient.blood_type && <Text style={styles.body}>Blood type: {patient.blood_type}</Text>}
        {allergies && <Text style={styles.body}>Allergies: {allergies}</Text>}
        {patient.emergency_contact_name && (
          <Text style={styles.body}>
            Emergency contact: {patient.emergency_contact_name}
            {patient.emergency_contact_phone ? ` -- ${patient.emergency_contact_phone}` : ""}
          </Text>
        )}
        {patient.dpd_deficiency_status && (
          <Text style={styles.badgeAccent}>DPD deficiency status: {patient.dpd_deficiency_status}</Text>
        )}
      </View>
    </View>
  );
}

function MedicationsBlock({ data }: { data: ExportData }) {
  return (
    <View>
      <Text style={styles.sectionHeader}>Current medications</Text>
      {data.medications.length === 0 ? (
        <Text style={styles.bodyMuted}>No current medications on record.</Text>
      ) : (
        <>
          <View style={styles.tableHeader}>
            <Text style={[styles.th, { flex: 2 }]}>Medication</Text>
            <Text style={[styles.th, { flex: 1 }]}>Dosage</Text>
            <Text style={[styles.th, { flex: 1 }]}>Frequency</Text>
            <Text style={[styles.th, { flex: 1 }]}>Prescriber</Text>
            <Text style={[styles.th, { width: 70 }]}>Start date</Text>
          </View>
          {data.medications.map((m) => (
            <View key={m.id} style={styles.tableRow}>
              <Text style={[styles.td, { flex: 2 }]}>{m.name ?? "Unnamed"}</Text>
              <Text style={[styles.td, { flex: 1 }]}>
                {m.dose ?? ""}
                {m.unit ?? ""}
              </Text>
              <Text style={[styles.td, { flex: 1 }]}>{m.frequency ?? ""}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{m.prescriber ?? ""}</Text>
              <Text style={[styles.td, { width: 70 }]}>{fmtDate(m.start_date)}</Text>
            </View>
          ))}
        </>
      )}
    </View>
  );
}

function SymptomsBlock({ data }: { data: ExportData }) {
  return (
    <View>
      <Text style={styles.sectionHeader}>Symptom log (last {data.dateRangeDays} days)</Text>
      {data.symptomLogs.length === 0 ? (
        <Text style={styles.bodyMuted}>No symptom logs in selected period.</Text>
      ) : (
        <>
          <View style={styles.tableHeader}>
            <Text style={[styles.th, { width: 80 }]}>Date</Text>
            <Text style={[styles.th, { flex: 2 }]}>Context</Text>
            <Text style={[styles.th, { width: 60 }]}>Severity</Text>
          </View>
          {data.symptomLogs.map((s) => (
            <View key={s.id} style={styles.tableRow}>
              <Text style={[styles.td, { width: 80 }]}>{fmtDate(s.created_at)}</Text>
              <Text style={[styles.td, { flex: 2 }]}>{s.condition_context ?? ""}</Text>
              <Text style={[styles.td, { width: 60 }]}>
                {typeof s.overall_severity === "number" ? `${s.overall_severity}/10` : "--"}
              </Text>
            </View>
          ))}
        </>
      )}
    </View>
  );
}

function AppointmentsBlock({ data }: { data: ExportData }) {
  return (
    <View>
      <Text style={styles.sectionHeader}>Recent appointments</Text>
      {data.appointments.length === 0 ? (
        <Text style={styles.bodyMuted}>No appointments on record.</Text>
      ) : (
        <>
          <View style={styles.tableHeader}>
            <Text style={[styles.th, { width: 80 }]}>Date</Text>
            <Text style={[styles.th, { flex: 1 }]}>Provider</Text>
            <Text style={[styles.th, { width: 70 }]}>Type</Text>
            <Text style={[styles.th, { flex: 1 }]}>Location</Text>
            <Text style={[styles.th, { width: 60 }]}>Status</Text>
          </View>
          {data.appointments.map((a) => (
            <View key={a.id} style={styles.tableRow}>
              <Text style={[styles.td, { width: 80 }]}>{fmtDate(a.datetime)}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{a.provider_name ?? ""}</Text>
              <Text style={[styles.td, { width: 70 }]}>{a.appointment_type ?? ""}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{a.location ?? ""}</Text>
              <Text style={[styles.td, { width: 60 }]}>{a.completed ? "Completed" : "Upcoming"}</Text>
            </View>
          ))}
        </>
      )}
    </View>
  );
}

function DocumentsBlock({ data }: { data: ExportData }) {
  return (
    <View>
      <Text style={styles.sectionHeader}>Documents</Text>
      {data.documents.length === 0 ? (
        <Text style={styles.bodyMuted}>No documents uploaded.</Text>
      ) : (
        data.documents.map((d) => (
          <View key={d.id} style={styles.documentItem}>
            <Text style={[styles.body, { fontFamily: "Helvetica-Bold" }]}>
              {d.title ?? d.file_name ?? "Document"}
            </Text>
            <Text style={styles.smallMuted}>
              {d.document_category ?? ""}
              {d.created_at ? ` -- uploaded ${fmtDate(d.created_at)}` : ""}
            </Text>
            {d.summary && (
              <Text style={styles.body}>
                {d.summary.length > 360 ? `${d.summary.slice(0, 360).trim()}...` : d.summary}
              </Text>
            )}
          </View>
        ))
      )}
    </View>
  );
}

function CareTeamBlock({ data }: { data: ExportData }) {
  return (
    <View>
      <Text style={styles.sectionHeader}>Care team</Text>
      {data.careTeam.length === 0 ? (
        <Text style={styles.bodyMuted}>No care team members on record.</Text>
      ) : (
        <>
          <View style={styles.tableHeader}>
            <Text style={[styles.th, { flex: 1.2 }]}>Name</Text>
            <Text style={[styles.th, { flex: 1 }]}>Role</Text>
            <Text style={[styles.th, { flex: 1 }]}>Specialty</Text>
            <Text style={[styles.th, { flex: 1 }]}>Phone</Text>
            <Text style={[styles.th, { flex: 1.2 }]}>Email</Text>
          </View>
          {data.careTeam.map((c) => (
            <View key={c.id} style={styles.tableRow}>
              <Text style={[styles.td, { flex: 1.2 }]}>
                {c.name ?? ""}
                {c.is_primary ? " (Primary)" : ""}
              </Text>
              <Text style={[styles.td, { flex: 1 }]}>{c.role ?? ""}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{c.specialty ?? ""}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{c.phone ?? ""}</Text>
              <Text style={[styles.td, { flex: 1.2 }]}>{c.email ?? ""}</Text>
            </View>
          ))}
        </>
      )}
    </View>
  );
}

function ProviderNotesBlock({ data }: { data: ExportData }) {
  if (data.providerNotes.length === 0) return null;
  return (
    <View>
      <Text style={styles.sectionHeader}>Provider notes</Text>
      {data.providerNotes.map((n) => (
        <View key={n.id} style={styles.noteCard}>
          <Text style={styles.smallMuted}>
            {n.note_type ?? "general"} -- {fmtDate(n.created_at)}
          </Text>
          <Text style={styles.body}>{n.note_text}</Text>
        </View>
      ))}
    </View>
  );
}

/**
 * Builds the @react-pdf Document tree. Single Page with `wrap` so the
 * fixed footer renders on every page; @react-pdf paginates content
 * automatically when sections overflow the LETTER size.
 */
export function buildHospitalGradeDocument(data: ExportData) {
  return (
    <Document
      title={`Clarifer Medical Summary -- ${data.patient.name ?? "Patient"}`}
      author={data.generatedBy || "Clarifer"}
      subject={data.patient.name ?? "Patient"}
      producer="Clarifer"
    >
      <Page size="LETTER" style={styles.page} wrap>
        <HeaderBlock data={data} />
        <DisclaimerBlock />
        <EmergencyBlock data={data} />
        <MedicationsBlock data={data} />
        <SymptomsBlock data={data} />
        <AppointmentsBlock data={data} />
        <DocumentsBlock data={data} />
        <CareTeamBlock data={data} />
        <ProviderNotesBlock data={data} />
        <Footer generatedAt={data.generatedAt} />
      </Page>
    </Document>
  );
}

/**
 * Renders the document to a binary PDF buffer. Caller is responsible
 * for streaming the bytes back without writing to disk.
 */
export async function renderHospitalGradePdf(data: ExportData): Promise<Uint8Array> {
  const doc = buildHospitalGradeDocument(data);
  const buffer = await renderToBuffer(doc);
  return buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
}
