/**
 * Sprint 8 — hospital-grade PDF export using @react-pdf/renderer.
 *
 * Build a multi-page PDF from a patient bundle. The output is a care
 * coordination summary, not a medical record -- every page footer says so.
 */

import * as React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

export interface PdfPatient {
  id: string;
  name: string;
  dob: string | null;
  custom_diagnosis: string | null;
  diagnosis_date: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
}
export interface PdfBiomarker {
  biomarker_type: string;
  status: string;
  value: string | null;
  tested_date: string | null;
  notes: string | null;
}
export interface PdfMedication {
  name: string;
  dose: string | null;
  unit: string | null;
  frequency: string | null;
  start_date: string | null;
}
export interface PdfSymptomSummary {
  day: string;
  severity: number;
}
export interface PdfDocument {
  title: string;
  summary: string | null;
  uploaded_at: string | null;
}
export interface PdfCareTeamMember {
  name: string;
  role: string;
  phone: string;
  email: string;
}
export interface PdfAppointment {
  title: string;
  datetime: string;
  provider_name: string | null;
  location: string | null;
  appointment_type: string | null;
}
export interface PdfBundle {
  patient: PdfPatient;
  caregiverName: string;
  primaryOncologist: string | null;
  biomarkers: PdfBiomarker[];
  medications: PdfMedication[];
  symptomSummary: PdfSymptomSummary[];
  dpdFluoropyrimidine: boolean;
  documents: PdfDocument[];
  careTeam: PdfCareTeamMember[];
  appointments: PdfAppointment[];
  generatedAt: string;
}

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, color: "#1A1A1A", fontFamily: "Helvetica" },
  coverTitle: { fontSize: 22, marginBottom: 8, color: "#2C5F4A" },
  coverSub: { fontSize: 12, marginBottom: 4 },
  h1: { fontSize: 16, marginBottom: 6, color: "#2C5F4A" },
  h2: { fontSize: 12, marginTop: 8, marginBottom: 4, color: "#2C5F4A" },
  body: { fontSize: 10, lineHeight: 1.5 },
  row: { flexDirection: "row", marginBottom: 2 },
  rowLabel: { width: 120, fontSize: 10, color: "#6B6B6B" },
  rowValue: { flex: 1, fontSize: 10 },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#E8E2D9", paddingVertical: 4 },
  tableHeader: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#2C5F4A", paddingBottom: 4 },
  col: { flex: 1, fontSize: 10, paddingRight: 6 },
  colNarrow: { width: 80, fontSize: 10, paddingRight: 6 },
  alert: { backgroundColor: "#FDF3EE", borderLeftWidth: 3, borderLeftColor: "#C4714A", padding: 8, marginVertical: 6 },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 36,
    right: 36,
    textAlign: "center",
    fontSize: 8,
    color: "#6B6B6B",
  },
  chartRow: { flexDirection: "row", alignItems: "flex-end", height: 80, borderBottomWidth: 0.5, borderBottomColor: "#E8E2D9" },
  bar: { backgroundColor: "#2C5F4A", marginRight: 2 },
  chartLabelRow: { flexDirection: "row", marginTop: 2 },
});

function Footer({ generatedAt }: { generatedAt: string }) {
  return React.createElement(
    Text,
    { style: styles.footer, fixed: true },
    `Generated by Clarifer on ${generatedAt} | clarifer.com | This is a care coordination tool, not a medical record. For medical decisions, consult your healthcare team.`
  );
}

function safe(v: string | null | undefined, fallback = "Not recorded"): string {
  return v && String(v).trim() ? String(v) : fallback;
}

function ageFromDob(dob: string | null): string {
  if (!dob) return "";
  const d = new Date(dob);
  const now = new Date();
  let age = now.getFullYear() - d.getFullYear();
  const m = now.getMonth() - d.getMonth();
  if (m < 0 || (m === 0 && now.getDate() < d.getDate())) age--;
  return String(age);
}

export function buildPatientPdfDocument(bundle: PdfBundle) {
  const p = bundle.patient;
  const generatedLabel = new Date(bundle.generatedAt).toLocaleDateString();

  const maxSeverity = Math.max(1, ...bundle.symptomSummary.map((s) => s.severity));
  const barWidth = bundle.symptomSummary.length === 0 ? 0 : 500 / bundle.symptomSummary.length - 2;
  const avgSeverity = bundle.symptomSummary.length === 0
    ? null
    : (bundle.symptomSummary.reduce((sum, s) => sum + s.severity, 0) / bundle.symptomSummary.length).toFixed(1);

  return React.createElement(
    Document,
    {
      title: `Clarifer Patient Summary -- ${p.name}`,
      author: bundle.caregiverName,
      subject: p.name,
      producer: "Clarifer",
    },
    // Page 1 — Cover
    React.createElement(
      Page,
      { key: "cover", size: "LETTER", style: styles.page },
      React.createElement(Text, { style: styles.coverTitle }, "Clarifer"),
      React.createElement(Text, { style: styles.coverSub }, "Patient Medical Summary"),
      React.createElement(Text, { style: { marginTop: 16 } }, safe(p.name)),
      React.createElement(Text, null, `DOB: ${safe(p.dob)}${p.dob ? ` · Age: ${ageFromDob(p.dob)}` : ""}`),
      React.createElement(Text, null, `Generated: ${generatedLabel}`),
      React.createElement(
        Text,
        { style: { marginTop: 24, lineHeight: 1.5 } },
        `This document is a care coordination summary prepared by ${bundle.caregiverName} using Clarifer. It is not a medical record.`
      ),
      React.createElement(Footer, { generatedAt: generatedLabel })
    ),
    // Page 2 — Patient information
    React.createElement(
      Page,
      { key: "patient", size: "LETTER", style: styles.page },
      React.createElement(Text, { style: styles.h1 }, "Patient information"),
      React.createElement(View, { style: styles.row },
        React.createElement(Text, { style: styles.rowLabel }, "Full name"),
        React.createElement(Text, { style: styles.rowValue }, safe(p.name))),
      React.createElement(View, { style: styles.row },
        React.createElement(Text, { style: styles.rowLabel }, "DOB / Age"),
        React.createElement(Text, { style: styles.rowValue }, `${safe(p.dob)}${p.dob ? ` · ${ageFromDob(p.dob)}` : ""}`)),
      React.createElement(View, { style: styles.row },
        React.createElement(Text, { style: styles.rowLabel }, "Diagnosis / stage"),
        React.createElement(Text, { style: styles.rowValue }, safe(p.custom_diagnosis))),
      React.createElement(View, { style: styles.row },
        React.createElement(Text, { style: styles.rowLabel }, "Condition"),
        React.createElement(Text, { style: styles.rowValue }, "Cholangiocarcinoma")),
      React.createElement(View, { style: styles.row },
        React.createElement(Text, { style: styles.rowLabel }, "Date of diagnosis"),
        React.createElement(Text, { style: styles.rowValue }, safe(p.diagnosis_date))),
      React.createElement(View, { style: styles.row },
        React.createElement(Text, { style: styles.rowLabel }, "Primary oncologist"),
        React.createElement(Text, { style: styles.rowValue }, safe(bundle.primaryOncologist))),
      React.createElement(View, { style: styles.row },
        React.createElement(Text, { style: styles.rowLabel }, "Emergency contact"),
        React.createElement(Text, { style: styles.rowValue }, `${safe(p.emergency_contact_name)} ${p.emergency_contact_phone ? `(${p.emergency_contact_phone})` : ""}`)),
      React.createElement(Footer, { generatedAt: generatedLabel })
    ),
    // Page 3 — Biomarkers
    React.createElement(
      Page,
      { key: "biomarkers", size: "LETTER", style: styles.page },
      React.createElement(Text, { style: styles.h1 }, "Biomarkers"),
      React.createElement(
        View, { style: styles.tableHeader },
        React.createElement(Text, { style: styles.col }, "Biomarker"),
        React.createElement(Text, { style: styles.colNarrow }, "Status"),
        React.createElement(Text, { style: styles.colNarrow }, "Date"),
        React.createElement(Text, { style: styles.col }, "Notes"),
      ),
      bundle.biomarkers.length === 0
        ? React.createElement(Text, { style: { marginTop: 6 } }, "No biomarker testing recorded.")
        : bundle.biomarkers.map((b, i) => React.createElement(
            View, { key: i, style: styles.tableRow },
            React.createElement(Text, { style: styles.col }, b.biomarker_type),
            React.createElement(Text, { style: styles.colNarrow }, b.status),
            React.createElement(Text, { style: styles.colNarrow }, safe(b.tested_date, "")),
            React.createElement(Text, { style: styles.col }, [b.value, b.notes].filter(Boolean).join(" · ") || ""),
          )),
      React.createElement(Footer, { generatedAt: generatedLabel })
    ),
    // Page 4 — Medications
    React.createElement(
      Page,
      { key: "medications", size: "LETTER", style: styles.page },
      React.createElement(Text, { style: styles.h1 }, "Medications"),
      bundle.dpdFluoropyrimidine && React.createElement(
        View, { style: styles.alert },
        React.createElement(Text, { style: { color: "#C4714A", fontSize: 11, marginBottom: 2 } }, "DPD screening alert"),
        React.createElement(Text, null, "This patient is on a fluoropyrimidine. CCF recommends DPD deficiency screening before first dose."),
      ),
      React.createElement(
        View, { style: styles.tableHeader },
        React.createElement(Text, { style: styles.col }, "Medication"),
        React.createElement(Text, { style: styles.colNarrow }, "Dose"),
        React.createElement(Text, { style: styles.col }, "Frequency"),
        React.createElement(Text, { style: styles.colNarrow }, "Since"),
      ),
      bundle.medications.map((m, i) => React.createElement(
        View, { key: i, style: styles.tableRow },
        React.createElement(Text, { style: styles.col }, m.name),
        React.createElement(Text, { style: styles.colNarrow }, `${safe(m.dose, "")} ${safe(m.unit, "")}`.trim()),
        React.createElement(Text, { style: styles.col }, safe(m.frequency, "")),
        React.createElement(Text, { style: styles.colNarrow }, safe(m.start_date, "")),
      )),
      React.createElement(Footer, { generatedAt: generatedLabel })
    ),
    // Page 5 — Symptom trend
    React.createElement(
      Page,
      { key: "symptoms", size: "LETTER", style: styles.page },
      React.createElement(Text, { style: styles.h1 }, "Symptom trend (30 days)"),
      avgSeverity !== null && React.createElement(Text, { style: { marginBottom: 8 } }, `Average overall severity: ${avgSeverity}/10`),
      bundle.symptomSummary.length === 0
        ? React.createElement(Text, null, "No symptom logs in this range.")
        : React.createElement(
            View, { style: styles.chartRow },
            bundle.symptomSummary.map((s, i) => React.createElement(View, {
              key: i,
              style: { ...styles.bar, width: barWidth, height: (s.severity / maxSeverity) * 70 + 2 },
            })),
          ),
      React.createElement(Footer, { generatedAt: generatedLabel })
    ),
    // Page 6 — Recent documents
    React.createElement(
      Page,
      { key: "documents", size: "LETTER", style: styles.page },
      React.createElement(Text, { style: styles.h1 }, "Recent documents"),
      bundle.documents.length === 0
        ? React.createElement(Text, null, "No documents uploaded yet.")
        : bundle.documents.map((d, i) => React.createElement(
            View, { key: i, style: { marginBottom: 8 } },
            React.createElement(Text, { style: styles.h2 }, safe(d.title, "Untitled")),
            React.createElement(Text, null, safe(d.uploaded_at, "")),
            React.createElement(Text, { style: { marginTop: 2 } }, safe(d.summary, "No summary yet.")),
          )),
      React.createElement(Footer, { generatedAt: generatedLabel })
    ),
    // Page 7 — Care team
    React.createElement(
      Page,
      { key: "care-team", size: "LETTER", style: styles.page },
      React.createElement(Text, { style: styles.h1 }, "Care team"),
      bundle.careTeam.length === 0
        ? React.createElement(Text, null, "No care team members on file.")
        : bundle.careTeam.map((m, i) => React.createElement(
            View, { key: i, style: { marginBottom: 6 } },
            React.createElement(Text, { style: styles.h2 }, m.name),
            React.createElement(Text, null, `${m.role} · ${m.phone} · ${m.email}`),
          )),
      React.createElement(Footer, { generatedAt: generatedLabel })
    ),
    // Page 8 — Appointments
    React.createElement(
      Page,
      { key: "appts", size: "LETTER", style: styles.page },
      React.createElement(Text, { style: styles.h1 }, "Upcoming appointments"),
      bundle.appointments.length === 0
        ? React.createElement(Text, null, "No upcoming appointments.")
        : bundle.appointments.slice(0, 3).map((a, i) => React.createElement(
            View, { key: i, style: { marginBottom: 6 } },
            React.createElement(Text, { style: styles.h2 }, safe(a.title, "Appointment")),
            React.createElement(Text, null, `${safe(a.datetime, "TBD")} · ${safe(a.provider_name, "")} · ${safe(a.location, "")}`),
            React.createElement(Text, null, `Type: ${safe(a.appointment_type, "")}`),
          )),
      React.createElement(Footer, { generatedAt: generatedLabel })
    ),
  );
}

export async function generatePatientPdf(bundle: PdfBundle): Promise<Uint8Array> {
  const doc = buildPatientPdfDocument(bundle);
  const buffer = await renderToBuffer(doc);
  // Node Buffer is a Uint8Array subclass.
  return buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
}
