#!/bin/bash
# =============================================================================
# advance-session.sh
# Clarifer autonomous build system — session queue manager
#
# What this does:
#   1. Reads SPRINT_STATUS.md to find the last completed session number
#   2. Reads CLARIFER_SPRINT_PLAN.md to extract the next session's task
#   3. Writes the task to CURRENT_SESSION.md (what Claude Code reads)
#   4. Logs the advance to clarifer-sessions.log
#   5. Optionally kicks off the Claude Code run immediately
#
# Run this:
#   Manually:     ./advance-session.sh
#   After a run:  called automatically at the end of run-clarifer-session.sh
#   On a schedule: cron calls run-clarifer-session.sh which calls this
#
# Files this touches:
#   SPRINT_STATUS.md    — tracks which sessions are done (you maintain this)
#   CURRENT_SESSION.md  — what Claude Code reads for its next task
#   docs/CLARIFER_SPRINT_PLAN.md — the master sprint plan (read-only)
#   ~/logs/clarifer-sessions.log — append-only log
# =============================================================================

set -euo pipefail

# --- Paths (adjust if your repo is in a different location) ---
REPO="/mnt/c/Users/esqui/clarifier"
SPRINT_PLAN="$REPO/docs/CLARIFER_SPRINT_PLAN.md"
SPRINT_STATUS="$REPO/SPRINT_STATUS.md"
CURRENT_SESSION="$REPO/CURRENT_SESSION.md"
LOG="/home/sesquina/logs/clarifer-sessions.log"
CLAUDE_BIN="/home/sesquina/.nvm/versions/node/v20.20.2/bin/claude"

# --- Colors for terminal output ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') | $1" | tee -a "$LOG"
}

# =============================================================================
# STEP 1: Find the last completed session number
# =============================================================================

if [ ! -f "$SPRINT_STATUS" ]; then
  log "INIT: SPRINT_STATUS.md not found — creating it. Starting from S0 (no sessions complete)."
  cat > "$SPRINT_STATUS" << 'EOF'
# Clarifer Sprint Status
# Format: S[number] | [branch] | [DONE/SKIP] | [date] | [notes]
# Add a line here after each session completes.
# This file is the source of truth for what has been built.

# COMPLETED SESSIONS — add below this line:
EOF
fi

# Extract the highest completed session number from SPRINT_STATUS.md
LAST_DONE=$(grep -E "^S[0-9]+" "$SPRINT_STATUS" | grep -E "DONE|SKIP" | \
  grep -oE "S[0-9]+" | grep -oE "[0-9]+" | sort -n | tail -1)

if [ -z "$LAST_DONE" ]; then
  LAST_DONE=0
fi

NEXT_SESSION=$((LAST_DONE + 1))
log "STATUS: Last completed session = S${LAST_DONE}. Next session = S${NEXT_SESSION}."

# =============================================================================
# STEP 2: Check if we are past the end of the sprint plan
# =============================================================================

MAX_SESSION=126

if [ "$NEXT_SESSION" -gt "$MAX_SESSION" ]; then
  log "COMPLETE: All 126 sessions done. Clarifer is launched. No more sessions to queue."
  echo -e "${GREEN}All 126 sessions complete. You built Clarifer.${NC}"
  exit 0
fi

# =============================================================================
# STEP 3: Extract the session task from the sprint plan
# =============================================================================

# The sprint plan uses the format:  **S[N]** `branch-name`
# We find the line with **S[N]** and capture everything until the next **S or ##

SESSION_BLOCK=$(awk "/\*\*S${NEXT_SESSION}\*\*/{found=1} found{print} found && /^\*\*S[0-9]+\*\*/ && !/\*\*S${NEXT_SESSION}\*\*/{exit} found && /^---/{exit}" "$SPRINT_PLAN" | head -40)

if [ -z "$SESSION_BLOCK" ]; then
  log "ERROR: Could not find S${NEXT_SESSION} in CLARIFER_SPRINT_PLAN.md."
  echo -e "${RED}ERROR: S${NEXT_SESSION} not found in sprint plan. Check CLARIFER_SPRINT_PLAN.md.${NC}"
  exit 1
fi

# Extract branch name from the backtick on the **S[N]** line
BRANCH=$(echo "$SESSION_BLOCK" | head -1 | grep -oP '`[^`]+`' | tr -d '`' | head -1)

if [ -z "$BRANCH" ]; then
  BRANCH="sprint-${NEXT_SESSION}-task"
  log "WARN: Could not parse branch name for S${NEXT_SESSION}. Using default: $BRANCH"
fi

log "QUEUE: Writing S${NEXT_SESSION} (branch: ${BRANCH}) to CURRENT_SESSION.md."

# =============================================================================
# STEP 4: Write CURRENT_SESSION.md
# =============================================================================

cat > "$CURRENT_SESSION" << SESSIONEOF
# CURRENT SESSION: S${NEXT_SESSION}
# Generated: $(date)
# Branch: ${BRANCH}
# Do not edit this file manually. It is managed by advance-session.sh.

## Task

${SESSION_BLOCK}

## Rules (non-negotiable)

1. Read docs/CLARIFER_MASTER_SESSION_PROMPT.md before doing anything else.
2. List the 10 rules back before starting work.
3. Never push to main. Commit to branch: ${BRANCH}
4. Never run SQL migrations. Write SQL to supabase/migrations/ only. Log as MIGRATION REQUIRED.
5. Never hardcode secrets. New env vars go in .env.example with a note.
6. Every new API route touching patient data needs: auth check, role check, org_id filter, audit_log write.
7. Definition of done: tsc = 0 errors, vitest all passing, feature works on desktop and mobile viewport.
8. Bugs found during this session go to SPRINT_LOG.md as DISCOVERED ISSUE. Do not fix inline.
9. Every new web page needs a corresponding mobile screen in apps/mobile/app/.
10. When in doubt, stop and write DECISION REQUIRED in SPRINT_LOG.md. Do not guess.

## Copy rules (non-negotiable)

- Never use "serious illness" anywhere
- No em dashes anywhere
- No hex color strings in components (exception: lib/pdf/hospital-grade-export.tsx)
- No condition names visible on caregiver-facing screens
- Entity name is Clarifer Corp, never Cassini Design Group

## When this session is complete

Run this in the terminal:
  echo "S${NEXT_SESSION} | ${BRANCH} | DONE | $(date '+%Y-%m-%d') | " >> SPRINT_STATUS.md

Then stop. Do not start the next session. Samira or the advance-session.sh script will queue it.
SESSIONEOF

echo -e "${GREEN}CURRENT_SESSION.md updated for S${NEXT_SESSION} (${BRANCH}).${NC}"
log "READY: S${NEXT_SESSION} is queued. Run run-clarifer-session.sh to start it."

# =============================================================================
# STEP 5: Show a summary in the terminal
# =============================================================================

echo ""
echo -e "${BLUE}=== SESSION QUEUED ===${NC}"
echo -e "Session:  ${YELLOW}S${NEXT_SESSION}${NC}"
echo -e "Branch:   ${YELLOW}${BRANCH}${NC}"
echo -e "Progress: ${LAST_DONE} of 126 complete (${NEXT_SESSION} starting)"
echo ""
echo "To start this session now:"
echo "  ./run-clarifer-session.sh"
echo ""
echo "Or it will start automatically at 6am via cron."
